/**
 * Automatically generated by the EPF PipelineConverter tool
 * Warning: This file serves as a starting point only, and ensure you check for any missing or incorrect values
 */
library "epf@main"
env.CNP_DEFAULT_JAVA_IMAGE='registry-dev.cigna.com/cnp/cnp-docker-maven-java11:1.0.2-dev-ov2'
env.GIT_CREDENTIAL='SVPDEVOP-CIG-CLONEA_UserPw'
boolean isProductionDeployment = env.BRANCH_NAME ==~ /^(release|hotfix).*/
List phasesToRun = [
    [
        moduleType: "maven",
        moduleName: "cnp-build-publish-maven-create",
        subCommand: "build",
        branchPattern: '.*',
        isProductionDeployment: false,
        args                  : [
            publish     : true,
            pomFile     : 'pom.xml',
            buildGoals  : "clean install -B -Dmaven.test.skip=true"
        ]
    ],
    [
        moduleType            : 'docker',
        branchPattern         : '.*',
        sdlcEnvironment       : 'dev',
        isProductionDeployment: false,
        moduleName            : 'cnp-build-image',
        subCommand            : 'buildimage',
        serviceAccount        : 'kaniko',
        args                  : [
            appendCommitIdToTag : true,
            artifact            : 'lookup:publishUrl',
            generateDockerFile  : true,
            org                 : 'pharmacylevelbenefits',
            pomPath             : 'pom.xml',
            skipBuildIfExists   : true
        ]
    ],
    [
            emailRecipients: 'E40968,EH7944,C7P8ZQ,G02801,EL7582,EN7125,C8F8R5',
            branchPattern: '.*',
            lintingTypes: [
                approvalrequest: [
                    timeOut: 120,
                    message: 'Do want to deploy the application to DEV-CANDIDATE?',
                    id: 'cnpApprove',
                    submitter: 'accounts\\eh7944, accounts\\g02801, accounts\\e40968, accounts\\el7582, accounts\\en7125,accounts\\c8f8r5,accounts\\c7p8zq',
                ]
            ]
        ],
    [
            moduleType            : 'openshift',
            moduleName            : 'cnp-deploy-argorollouts',
            subCommand            : 'deploy',
            branchPattern         : '.*',
            sdlcEnvironment       : 'dev',
            isProductionDeployment: false,
            args                  : [
                appName                       : 'pharmacylevelbenefit-rxb-intent-1-dev',
                namespace                     : 'plb-dev',
                platform                      : 'OpenShift',
                ingressBaseHost               : 'apps-2.hs-3-nonprod.openshift.evernorthcloud.com',
                imageName                     : 'lookup:imageName',
                imageTag                      : 'lookup:tagName',
                configRepo                    : 'https://github.sys.cigna.com/cigna/plb-dev-argocd',
                useArgoCD                     : 'true',
                argoAppName                   : 'pharmacylevelbenefit-rxb-intent-1-dev',
                server                        : 'https://api.hs-3-nonprod.openshift.evernorthcloud.com:6443',
                argoCDServer                  : 'argocd-devops.apps.hs-3-nonprod.openshift.evernorthcloud.com',
                cluster                       : 'hs-3-nonprod',
                configDir                     : 'dev',
                env                           : 'dev',
                monitoringSolution           : 'newrelic',
                timeout                       : '90s',
                valuesFile                    : 'preview-values.yaml',
                progressingRetryCount         : 5
            ]
        ],
    [
                emailRecipients: 'E40968,EH7944,C7P8ZQ,G02801,EL7582,EN7125,C8F8R5',
                branchPattern: '.*',
                lintingTypes: [
                    approvalrequest: [
                        timeOut: 120,
                        message: 'Do want to deploy the application to DEV with Actual Topics?',
                        id: 'cnpApprove',
                        submitter: 'accounts\\eh7944, accounts\\g02801, accounts\\e40968, accounts\\el7582, accounts\\en7125,accounts\\c8f8r5,accounts\\c7p8zq',
                    ]
                ]
            ],
    [
        moduleType            : 'openshift',
        moduleName            : 'cnp-deploy-argorollouts',
        subCommand            : 'deploy',
        branchPattern         : '.*',
        sdlcEnvironment       : 'dev',
        isProductionDeployment: false,
        args                  : [
            appName                       : 'pharmacylevelbenefit-rxb-intent-1-dev',
            namespace                     : 'plb-dev',
            platform                      : 'OpenShift',
            ingressBaseHost               : 'apps-2.hs-3-nonprod.openshift.evernorthcloud.com',
            imageName                     : 'lookup:imageName',
            imageTag                      : 'lookup:tagName',
            configRepo                    : 'https://github.sys.cigna.com/cigna/plb-dev-argocd',
            useArgoCD                     : 'true',
            argoAppName                   : 'pharmacylevelbenefit-rxb-intent-1-dev',
            server                        : 'https://api.hs-3-nonprod.openshift.evernorthcloud.com:6443',
            argoCDServer                  : 'argocd-devops.apps.hs-3-nonprod.openshift.evernorthcloud.com',
            cluster                       : 'hs-3-nonprod',
            configDir                     : 'dev',
            env                           : 'dev',
            monitoringSolution           : 'newrelic',
            timeout                       : '90s',
            progressingRetryCount         : 5
        ]
    ],
    [
                    emailRecipients: 'E40968,EH7944,C7P8ZQ,G02801,EL7582,EN7125,C8F8R5',
                    branchPattern: '.*',
                    lintingTypes: [
                        approvalrequest: [
                            timeOut: 120,
                            message: 'Do want to deploy the application to DEV Cutover?',
                            id: 'cnpApprove',
                            submitter: 'accounts\\eh7944, accounts\\g02801, accounts\\e40968, accounts\\el7582, accounts\\en7125,accounts\\c8f8r5,accounts\\c7p8zq',
                        ]
                    ]
                ],
    [
        moduleType            : 'openshift',
        moduleName            : 'cnp-deploy-argorollouts',
        subCommand            : 'promote',
        branchPattern         : '.*', // need to check
        sdlcEnvironment       : 'dev',
        isProductionDeployment : false,
        args                  : [
            appName                       : 'pharmacylevelbenefit-rxb-intent-1-dev',
            namespace                     : 'plb-dev',
            platform                      : 'OpenShift',
            cluster                       : 'hs-3-nonprod',
            configDir                     : 'dev',
            progressingRetryCount         : 4,
            timeout                       : '30s',
            server                        : 'https://api.hs-3-nonprod.openshift.evernorthcloud.com:6443',
            env                           : 'dev'
        ]
    ],
    [
        emailRecipients: 'E40968,EH7944,C7P8ZQ,G02801,EL7582,EN7125,C8F8R5',
        branchPattern: '.*',
        lintingTypes: [
            approvalrequest: [
                timeOut: 120,
                message: 'Do want to deploy the application to QA-CANDIDATE?',
                id: 'cnpApprove',
                submitter: 'accounts\\eh7944, accounts\\g02801, accounts\\e40968, accounts\\el7582, accounts\\en7125,accounts\\c8f8r5,accounts\\c7p8zq',
            ]
        ]
    ],
    [
        moduleType            : 'openshift',
        moduleName            : 'cnp-deploy-argorollouts',
        subCommand            : 'deploy',
        branchPattern         : '.*',
        sdlcEnvironment       : 'qa',
        isProductionDeployment: false,
        args                  : [
            appName                       : 'pharmacylevelbenefit-rxb-intent-1-qa',
            namespace                     : 'plb-qa',
            platform                      : 'OpenShift',
            ingressBaseHost               : 'apps-2.hs-3-nonprod.openshift.evernorthcloud.com',
            imageName                     : 'lookup:imageName',
            imageTag                      : 'lookup:tagName',
            configRepo                    : 'https://github.sys.cigna.com/cigna/plb-qa-argocd',
            useArgoCD                     : 'true',
            argoAppName                   : 'pharmacylevelbenefit-rxb-intent-1-qa',
            server                        : 'https://api.hs-3-nonprod.openshift.evernorthcloud.com:6443',
            argoCDServer                  : 'argocd-devops.apps.hs-3-nonprod.openshift.evernorthcloud.com',
            cluster                       : 'hs-3-nonprod',
            configDir                     : 'qa',
            env                           : 'qa',
            monitoringSolution           : 'newrelic',
            timeout                       : '240s',
            valuesFile                    : 'preview-values.yaml',
            progressingRetryCount         : 5
        ]
    ],
    [
            emailRecipients: 'E40968,EH7944,C7P8ZQ,G02801,EL7582,EN7125,C8F8R5',
            branchPattern: '.*',
            lintingTypes: [
                approvalrequest: [
                    timeOut: 120,
                    message: 'Do want to deploy the application to QA with Actual topics?',
                    id: 'cnpApprove',
                    submitter: 'accounts\\eh7944, accounts\\g02801, accounts\\e40968, accounts\\el7582, accounts\\en7125,accounts\\c8f8r5,accounts\\c7p8zq',
                ]
            ]
        ],
    [
            moduleType            : 'openshift',
            moduleName            : 'cnp-deploy-argorollouts',
            subCommand            : 'deploy',
            branchPattern         : '.*',
            sdlcEnvironment       : 'qa',
            isProductionDeployment: false,
            args                  : [
                appName                       : 'pharmacylevelbenefit-rxb-intent-1-qa',
                namespace                     : 'plb-qa',
                platform                      : 'OpenShift',
                ingressBaseHost               : 'apps-2.hs-3-nonprod.openshift.evernorthcloud.com',
                imageName                     : 'lookup:imageName',
                imageTag                      : 'lookup:tagName',
                configRepo                    : 'https://github.sys.cigna.com/cigna/plb-qa-argocd',
                useArgoCD                     : 'true',
                argoAppName                   : 'pharmacylevelbenefit-rxb-intent-1-qa',
                server                        : 'https://api.hs-3-nonprod.openshift.evernorthcloud.com:6443',
                argoCDServer                  : 'argocd-devops.apps.hs-3-nonprod.openshift.evernorthcloud.com',
                cluster                       : 'hs-3-nonprod',
                configDir                     : 'qa',
                env                           : 'qa',
                monitoringSolution           : 'newrelic',
                timeout                       : '240s',
                progressingRetryCount         : 5
            ]
        ],
        [
                    emailRecipients: 'E40968,EH7944,C7P8ZQ,G02801,EL7582,EN7125,C8F8R5',
                    branchPattern: '.*',
                    lintingTypes: [
                        approvalrequest: [
                            timeOut: 120,
                            message: 'Do want to deploy the application to QA Cutover?',
                            id: 'cnpApprove',
                            submitter: 'accounts\\eh7944, accounts\\g02801, accounts\\e40968, accounts\\el7582, accounts\\en7125,accounts\\c8f8r5,accounts\\c7p8zq',
                        ]
                    ]
                ],
    [
        moduleType            : 'openshift',
        moduleName            : 'cnp-deploy-argorollouts',
        subCommand            : 'promote',
        branchPattern         : '.*',
        sdlcEnvironment       : 'qa',
        isProductionDeployment: false,
        args                  : [
            appName                       : 'pharmacylevelbenefit-rxb-intent-1-qa',
            namespace                     : 'plb-qa',
            platform                      : 'OpenShift',
            cluster                       : 'hs-3-nonprod',
            configDir                     : 'qa',
            progressingRetryCount         : 4,
            timeout                       : '30s',
            server                        : 'https://api.hs-3-nonprod.openshift.evernorthcloud.com:6443',
            env                           : 'qa'
        ]
    ],
    [
                            emailRecipients: 'E40968,EH7944,C7P8ZQ,G02801,EL7582,EN7125,C8F8R5',
                            branchPattern: '^(develop|release|hotfix).*',
                            lintingTypes: [
                                approvalrequest: [
                                    timeOut: 120,
                                    message: 'Do want to deploy the application to Prod Candidate?',
                                    id: 'cnpApprove',
                                    submitter: 'accounts\\eh7944, accounts\\g02801, accounts\\e40968, accounts\\el7582, accounts\\en7125,accounts\\c8f8r5,accounts\\c7p8zq',
                                ]
                            ]
                        ],

        [
                 moduleType            : 'docker',
                 branchPattern         : '^(develop|release|hotfix).*',
                 sdlcEnvironment       : 'prod',
                 isProductionDeployment: true,
                 moduleName            : 'cnp-publish-image',
                 subCommand            : 'publishimage',
                 serviceAccount        : 'kaniko',
                 args                  : [
                 sourceImage           : 'lookup:publishUrl',
                 signImage             : true,
                 repository            : 'registry.cigna.com'
                 ]
             ],
             [
                 releaseType: 'preRelease',
                 branchPattern: '^(develop|release|hotfix).*',
                 phases: [
                     [
                             moduleType            : 'openshift',
                             moduleName            : 'cnp-deploy-argorollouts',
                             subCommand            : 'deploy',
                             branchPattern         : '^(release|hotfix).*',
                             sdlcEnvironment       : 'prod',
                             isProductionDeployment: true,
                             args                  : [
                                 appName                       : 'pharmacylevelbenefit-rxb-intent-1-prod',
                                 namespace                     : 'plb-prod',
                                 platform                      : 'OpenShift',
                                 ingressBaseHost               : 'apps-1.hs-2-prod.openshift.evernorthcloud.com',
                                 imageName                     : 'lookup:imageName',
                                 imageTag                      : 'lookup:tagName',
                                 configRepo                    : 'https://github.sys.cigna.com/cigna/plb-prod-argocd',
                                 useArgoCD                     : 'true',
                                 argoAppName                   : 'pharmacylevelbenefit-rxb-intent-1-prod',
                                 server                        : 'https://api.hs-2-prod.openshift.evernorthcloud.com:6443',
                                 argoCDServer                  : 'argocd-devops.apps.hs-2-prod.openshift.evernorthcloud.com',
                                 cluster                       : 'hs-2-prod',
                                 configDir                     : 'prod',
                                 env                           : 'prod',
                                 monitoringSolution            : 'newrelic',
                                 timeout                       : '120s',
                                 valuesFile                    : 'preview-values.yaml',
                                 progressingRetryCount         : 5
                             ]
                         ]
                 ]
             ],
             [
                 releaseType: 'release',
                 branchPattern: '^(develop|release|hotfix).*',
                 phases: [
                 [
                                                  emailRecipients: 'E40968,EH7944,C7P8ZQ,G02801,EL7582,EN7125,C8F8R5',
                                                  branchPattern: '^(release|hotfix).*',
                                                  lintingTypes: [
                                                      approvalrequest: [
                                                          timeOut: 120,
                                                          message: 'Do want to deploy the application to Prod with Actual Topics?',
                                                          id: 'cnpApprove',
                                                          submitter: 'accounts\\eh7944, accounts\\g02801, accounts\\e40968, accounts\\el7582, accounts\\en7125,accounts\\c8f8r5,accounts\\c7p8zq',
                                                      ]
                                                  ]
                                              ],
                     [
                                              moduleType            : 'openshift',
                                              moduleName            : 'cnp-deploy-argorollouts',
                                              subCommand            : 'deploy',
                                              branchPattern         : '^(release|hotfix).*',
                                              sdlcEnvironment       : 'prod',
                                              isProductionDeployment: true,
                                              args                  : [
                                                  appName                       : 'pharmacylevelbenefit-rxb-intent-1-prod',
                                                  namespace                     : 'plb-prod',
                                                  platform                      : 'OpenShift',
                                                  ingressBaseHost               : 'apps-1.hs-2-prod.openshift.evernorthcloud.com',
                                                  imageName                     : 'lookup:imageName',
                                                  imageTag                      : 'lookup:tagName',
                                                  configRepo                    : 'https://github.sys.cigna.com/cigna/plb-prod-argocd',
                                                  useArgoCD                     : 'true',
                                                  argoAppName                   : 'pharmacylevelbenefit-rxb-intent-1-prod',
                                                  server                        : 'https://api.hs-2-prod.openshift.evernorthcloud.com:6443',
                                                  argoCDServer                  : 'argocd-devops.apps.hs-2-prod.openshift.evernorthcloud.com',
                                                  cluster                       : 'hs-2-prod',
                                                  configDir                     : 'prod',
                                                  env                           : 'prod',
                                                  monitoringSolution            : 'newrelic',
                                                  timeout                       : '120s',
                                                  progressingRetryCount         : 5
                                              ]
                                          ],
             [
                                     emailRecipients: 'E40968,EH7944,C7P8ZQ,G02801,EL7582,EN7125,C8F8R5',
                                     branchPattern: '^(release|hotfix).*',
                                     lintingTypes: [
                                         approvalrequest: [
                                             timeOut: 120,
                                             message: 'Do want to perform Prod cutover?',
                                             id: 'cnpApprove',
                                             submitter: 'accounts\\eh7944, accounts\\g02801, accounts\\e40968, accounts\\el7582, accounts\\en7125,accounts\\c8f8r5,accounts\\c7p8zq',
                                         ]
                                     ]
                                 ],
             [
                     moduleType            : 'openshift',
                     moduleName            : 'cnp-deploy-argorollouts',
                     subCommand            : 'promote',
                     branchPattern         : '^(release|hotfix).*',
                     sdlcEnvironment       : 'prod',
                     isProductionDeployment: true,
                     args                  : [
                         appName                       : 'pharmacylevelbenefit-rxb-intent-1-prod',
                         namespace                     : 'plb-prod',
                         platform                      : 'OpenShift',
                         cluster                       : 'hs-2-prod',
                         configDir                     : 'prod',
                         progressingRetryCount         : 4,
                         timeout                       : '30s',
                         server                        : 'https://api.hs-2-prod.openshift.evernorthcloud.com:6443',
                         env                           : 'prod'
                     ]
                 ]
             ]
        ]
      ]

cignaBuildFlow {
    githubConnectionName = 'github'
    commitStatusName = 'pharmacylevelbenefit-rxb-intent'
    cloudName = 'pbplb-openshift-devops1'
    githubCredentialsId = 'GIT_TOKEN'
    phases = phasesToRun
}