customJavaOpts: "-javaagent:/app/lib/newrelic-agent-7.5.0.jar
  -Dspring.profiles.active=service
  -Dspring.config.location=classpath:bootstrap.yml,classpath:properties/openshift/common/application.properties
  -Dspring.cloud.config.enable=true
  -Dlogging.config=classpath:properties/common/log4j2.properties
  -Dspring.cloud.config.uri=https://config-server-qa.express-scripts.com/config
  -Dspring.application.name=pharmacylevelbenefit-fullintent-1-qa
  -Dspring.cloud.config.name=pharmacylevelbenefit-fullintent,pharmacyLevelBenefit-kafka_openshift,pharmacylevelBenefits-fullIntent-errors,pharmacylevelbenefits-reportingapi
  -Dspring.cloud.config.profile=pharmacylevelbenefit-fullintent,pharmacyLevelBenefit-kafka_openshift,pharmacylevelBenefits-fullIntent-errors,pharmacylevelbenefits-reportingapi"

maxHeapSize: 600m

resources:
  requests:
    memory: 500Mi
    cpu: 800m
  limits:
    memory: 1.1Gi


readinessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 240
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 30

livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 240
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 30

hpa:
  minReplicas: 2
  maxReplicas: 4

#configureHpa: false
#replicas: 0

customEnv:

  - name: config.key.pharmacylevelbenefit-fullintent.1
    valueFrom:
      secretKeyRef:
        name: pharmacylevelbenefit-fullintent-config
        key: config.key.pharmacylevelbenefit-fullintent.1

  - name: config.key.pharmacylevelBenefits-fullIntent-errors.1
    valueFrom:
      secretKeyRef:
        name: pharmacylevelbenefit-fullintent-config
        key: config.key.pharmacylevelBenefits-fullIntent-errors.1

  - name: config.key.pharmacyLevelBenefit-kafka_openshift.1
    valueFrom:
      secretKeyRef:
        name: pharmacylevelbenefit-fullintent-config
        key: config.key.pharmacyLevelBenefit-kafka_openshift.1

  - name: config.key.pharmacylevelbenefits-reportingapi.2
    valueFrom:
      secretKeyRef:
        name: pharmacylevelbenefit-fullintent-config
        key: config_key_pharmacylevelbenefits_reportingapi_2

  - name: vcap.services.plb-consume-bef-authinator.consumerKey
    valueFrom:
      secretKeyRef:
        name: plb-consume-bef
        key: consumerKey

  - name: vcap.services.plb-consume-bef-authinator.consumerSecret
    valueFrom:
      secretKeyRef:
        name: plb-consume-bef
        key: consumerSecret

  - name: messaging.destination1
    value: "TP.BEF.ERRORS"

  - name: messaging.destination2
    value: "TP.BEF.PHARMACY.BENEFIT.IMPLEMENTED"

  - name: messaging.destination3
    value: "TP.BEF.PLB.FULL.INTENT.REQUEST"

  - name: messaging.destination4
    value: "TP.BEF.PLB.FULL.INTENT.RESPONSE"